# Generated by Django 5.2.5 on 2025-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=20, unique=True),
        ),
    ]
