# Generated by Django 5.2.5 on 2025-10-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuario', '0003_perfilusuario_area_unidad_perfilusuario_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='area_unidad',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='mfa_habilitado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ultimo_acceso',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=20, unique=True),
        ),
    ]
