# Generated by Django 5.2.5 on 2025-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuario', '0004_remove_perfilusuario_area_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='area_unidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado'), ('DESACTIVADO', 'Desactivado')], default='ACTIVO', max_length=12),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='mfa_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('supervisor', 'Supervisor')], max_length=20, unique=True),
        ),
    ]
