# Generated by Django 5.2.5 on 2025-10-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0002_remove_producto_categoria_delete_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('ean_upc', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='EAN/UPC')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('uom_compra', models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('DOCENA', 'Docena'), ('GRAMO', 'Gramo'), ('PAQUETE', 'Paquete')], max_length=10, verbose_name='Unidad de Compra')),
                ('uom_venta', models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('DOCENA', 'Docena'), ('GRAMO', 'Gramo'), ('PAQUETE', 'Paquete')], max_length=10, verbose_name='Unidad de Venta')),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Factor de Conversión')),
                ('costo_estandar', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Costo Estándar')),
                ('costo_promedio', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Costo Promedio')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Precio de Venta')),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='IVA (%)')),
                ('stock_minimo', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Stock Máximo')),
                ('punto_reorden', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Punto de Reorden')),
                ('perishable', models.BooleanField(default=False, verbose_name='Es Perecedero')),
                ('control_por_lote', models.BooleanField(default=False, verbose_name='Control por Lote')),
                ('control_por_serie', models.BooleanField(default=False, verbose_name='Control por Serie')),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de Imagen')),
                ('ficha_tecnica_url', models.URLField(blank=True, verbose_name='URL Ficha Técnica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['sku'],
            },
        ),
    ]
