# Generated by Django 5.2.5 on 2025-10-03 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del proveedor', max_length=100, verbose_name='Nombre del Proveedor')),
                ('razon_social', models.CharField(blank=True, help_text='Razón social legal de la empresa proveedora', max_length=150, null=True, verbose_name='Razón Social')),
                ('rfc', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes del proveedor', max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('telefono', models.CharField(help_text='Número telefónico principal del proveedor', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del proveedor', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(help_text='Dirección física del proveedor', max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde se ubica el proveedor', max_length=100, null=True, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal de la dirección del proveedor', max_length=10, null=True, verbose_name='Código Postal')),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Número de días de crédito que otorga el proveedor', verbose_name='Días de Crédito')),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento por pronto pago', max_digits=5, verbose_name='Descuento Pronto Pago (%)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Límite de crédito otorgado por el proveedor', max_digits=12, verbose_name='Límite de Crédito')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el proveedor está activo para realizar compras', verbose_name='Proveedor Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el proveedor', verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Modificación')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el proveedor', null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, help_text='Número único de identificación de la orden de compra', max_length=20, null=True, unique=True, verbose_name='Número de Orden')),
                ('fecha', models.DateField(help_text='Fecha en que se realizó la orden de compra', verbose_name='Fecha de la Orden')),
                ('fecha_entrega_esperada', models.DateField(blank=True, help_text='Fecha esperada para la entrega de los productos', null=True, verbose_name='Fecha de Entrega Esperada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada al Proveedor'), ('confirmada', 'Confirmada por Proveedor'), ('parcial', 'Entrega Parcial'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la orden de compra', max_length=20, verbose_name='Estado de la Orden')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal de la orden (sin impuestos)', max_digits=12, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de impuestos aplicados', max_digits=12, verbose_name='Impuestos')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento aplicado a la orden', max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final de la orden de compra', max_digits=12, verbose_name='Total de la Orden')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la orden de compra', null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(help_text='Usuario del sistema que está realizando esta orden de compra', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realiza la Compra')),
                ('proveedor', models.ForeignKey(help_text='Proveedor al que se le está comprando', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del producto a comprar', verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto en esta compra', max_digits=10, verbose_name='Precio Unitario')),
                ('descuento_linea', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento aplicado específicamente a esta línea', max_digits=8, verbose_name='Descuento por Línea')),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal de esta línea (cantidad × precio_unitario - descuento)', max_digits=12, verbose_name='Subtotal de Línea')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, help_text='Cantidad realmente recibida del producto', verbose_name='Cantidad Recibida')),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha en que se recibió el producto', null=True, verbose_name='Fecha de Recepción')),
                ('notas_detalle', models.TextField(blank=True, help_text='Notas específicas sobre este producto en la orden', null=True, verbose_name='Notas del Detalle')),
                ('producto', models.ForeignKey(help_text='Producto que se está comprando', on_delete=django.db.models.deletion.CASCADE, to='produccion.producto', verbose_name='Producto')),
                ('orden', models.ForeignKey(help_text='Orden de compra a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Código interno que usa el proveedor para este producto', max_length=50, null=True, verbose_name='Código del Proveedor')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio de compra del producto a este proveedor', max_digits=10, verbose_name='Precio de Compra')),
                ('precio_con_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento aplicado (si aplica)', max_digits=10, null=True, verbose_name='Precio con Descuento')),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=1, help_text='Días que tarda el proveedor en entregar este producto', verbose_name='Tiempo de Entrega (días)')),
                ('cantidad_minima', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de pedido para este producto', verbose_name='Cantidad Mínima')),
                ('es_proveedor_preferido', models.BooleanField(default=False, help_text='Indica si este es el proveedor preferido para este producto', verbose_name='Proveedor Preferido')),
                ('fecha_ultimo_precio', models.DateField(auto_now=True, help_text='Fecha de la última actualización de precio', verbose_name='Fecha Último Precio')),
                ('producto', models.ForeignKey(help_text='Producto que suministra el proveedor', on_delete=django.db.models.deletion.CASCADE, to='produccion.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que suministra el producto', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'ordering': ['producto__nombre', 'proveedor__nombre'],
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
